
// Objective-C API for talking to the following Go packages
//
//	dnsly.app/tunnel/tunnel
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tunnel_FRAMEWORK_H__
#define __Tunnel_FRAMEWORK_H__

#include "Tunnel.objc.h"
#include "Universe.objc.h"

#endif
