// Objective-C API for talking to dnsly.app/tunnel/tunnel Go package.
//   gobind -lang=objc dnsly.app/tunnel/tunnel
//
// File is generated by gobind. Do not edit.

#ifndef __Tunnel_H__
#define __Tunnel_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TunnelConfig;

/**
 * Config is the tunnel configuration. All fields are plain strings/ints so
gomobile can pass them without reflection issues.
 */
@interface TunnelConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * TunnelType selects the transport: "ssh", "vayDnsSsh", "socks5",
"vayDnsSocks", "vaydns", "vayDns".
 */
@property (nonatomic) NSString* _Nonnull tunnelType;
/**
 * Server / Port are the upstream SOCKS5 server (socks5 mode) or the
VayDNS server (dns mode).
 */
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) long port;
/**
 * Domain is the DNS tunnel domain (vaydns mode).
 */
@property (nonatomic) NSString* _Nonnull domain;
/**
 * DnsResolver is the upstream resolver IP used in dns tunnel mode.
 */
@property (nonatomic) NSString* _Nonnull dnsResolver;
@property (nonatomic) NSString* _Nonnull dnsTransport;
@property (nonatomic) NSString* _Nonnull recordType;
@property (nonatomic) long queryLength;
/**
 * SSH credentials.
 */
@property (nonatomic) NSString* _Nonnull sshHost;
@property (nonatomic) long sshPort;
@property (nonatomic) NSString* _Nonnull sshUser;
@property (nonatomic) NSString* _Nonnull sshPassword;
@property (nonatomic) NSString* _Nonnull sshKey;
/**
 * SOCKS5 upstream credentials (socks5 mode).
 */
@property (nonatomic) NSString* _Nonnull socksUser;
@property (nonatomic) NSString* _Nonnull socksPassword;
@property (nonatomic) long mtu;
@property (nonatomic) long timeout;
@end

/**
 * IsRunning reports whether a tunnel is currently active.
 */
FOUNDATION_EXPORT BOOL TunnelIsRunning(void);

/**
 * LastError returns the last tunnel error as a string (empty if none).
Reserved for future use; currently always returns "".
 */
FOUNDATION_EXPORT NSString* _Nonnull TunnelLastError(void);

/**
 * Start parses configJSON, launches the appropriate transport, and returns the
local SOCKS5 port that Tun2Socks should connect to.
Returns -1 on error.
 */
FOUNDATION_EXPORT long TunnelStart(NSString* _Nullable configJSON);

/**
 * Stop shuts down the active tunnel.
 */
FOUNDATION_EXPORT void TunnelStop(void);

#endif
